[workspace]
members = [
    "kms",
    "kms-rpc",
    "ra-rpc",
    "ra-tls",
    "tdx-attest-sys",
    "tdx-attest",
    "tdxctl",
    "iohash",
    "tappd",
    "tappd-rpc",
]
resolver = "2"

[patch.crates-io]
dcap-qvl = { git = "https://github.com/Phala-Network/dcap-qvl.git" }
