[workspace]
members = [
    "kms",
    "kms/rpc",
    "ra-rpc",
    "ra-tls",
    "tdx-attest-sys",
    "tdx-attest",
    "tdxctl",
    "iohash",
    "tappd",
    "tappd/rpc",
    "teepod",
    "teepod/rpc",
    "tproxy",
    "tproxy/rpc",
    "certgen",
    "certbot",
    "certbot/cli",
    "ct_monitor",
]
resolver = "2"
