[package]
name = "iohash"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.87"
blake2 = "0.10.6"
clap = { version = "4.5.17", features = ["derive"] }
fs-err = "2.11.0"
hex_fmt = "0.3.0"
sha2 = "0.10.8"
sha3 = "0.10.8"
