[default]
workers = 8
max_blocking = 64
ident = "Tappd Server"
temp_dir = "/tmp"
keep_alive = 10
log_level = "debug"
address = "unix:/var/run/tappd.sock"
reuse = false
cert_file = "/etc/tappd/cert.pem"
key_file = "/etc/tappd/key.pem"
