workers = 8
max_blocking = 64
ident = "Tproxy Server"
temp_dir = "/tmp"
keep_alive = 10
log_level = "debug"
port = 8010

[core]
pccs_url = "https://api.trustedservices.intel.com/tdx/certification/v4"
state_path = "./tproxy-state.json"

[core.certbot]
workdir = "/etc/certbot"

[core.wg]
public_key = ""
private_key = ""
ip = "10.0.0.1"
listen_port = 51820
client_ip_range = "10.0.0.0/24"
config_path = "/etc/wireguard/wg0.conf"
interface = "wg0"
endpoint = "10.0.2.2:51820"

[core.proxy]
cert_chain = "/etc/rproxy/certs/cert.pem"
cert_key = "/etc/rproxy/certs/key.pem"
base_domain = "app.localhost"
listen_addr = "0.0.0.0"
listen_port = 8443
tappd_port = 8090

[core.recycle]
enabled = true
interval = "5m"
timeout = "10h"
