[package]
name = "tdx-attest-sys"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

[build-dependencies]
bindgen = "0.70.1"
cc = "1.1.20"
