[package]
name = "teepod"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bon = "2.0.1"
dirs = "5.0.1"
hex = "0.4.3"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
sha2 = "0.10.8"
shared_child = "1.0.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
literal = "0.2.0"
