workers = 8
max_blocking = 64
ident = "Teepod Server"
temp_dir = "/tmp"
keep_alive = 10
log_level = "debug"
port = 8080

[cvm]
ca_cert = "../certs/ca.cert"
tmp_ca_cert = "../certs/tmp-ca.cert"
tmp_ca_key = "../certs/tmp-ca.key"
kms_url = "http://127.0.0.1:8081"
tproxy_url = "http://127.0.0.1:8082"