workers = 8
max_blocking = 64
ident = "Phala KMS"
temp_dir = "/tmp"
keep_alive = 10
log_level = "info"
address = "0.0.0.0"
port = 8043

[tls]
key = "/etc/kms/certs/key.pem"
certs = "/etc/kms/certs/cert.pem"

[tls.mutual]
ca_certs = "/etc/kms/certs/ca.cert"
mandatory = false

[core]
root_ca_cert = "/etc/kms/certs/ca.cert"
root_ca_key = "/etc/kms/certs/ca.key"
subject_postfix = ".local"
cert_log_dir = "/var/log/kms"
allow_any_upgrade = false
upgrade_registry_dir = "/var/run/kms/upgrade_registry"
pccs_url = "https://api.trustedservices.intel.com/tdx/certification/v4"

[core.allowed_mr]
allow_all = false
mrtd = []
rtmr0 = []
rtmr1 = []
rtmr2 = []
