[default]
workers = 8
max_blocking = 64
ident = "Phala KMS"
temp_dir = "/tmp"
keep_alive = 10
log_level = "debug"
address = "0.0.0.0"
port = 8043

[default.tls]
key = "../certs/kms-rpc.key"
certs = "../certs/kms-rpc.cert"

[default.tls.mutual]
ca_certs = "../certs/tmp-ca.cert"
mandatory = false

[default.limits]
bytes = "8KiB"
data-form = "2MiB"
file = "1MiB"
form = "32KiB"
json = "1MiB"
msgpack = "1MiB"
string = "8KiB"

[core]
root_ca_cert = "../certs/ca.cert"
root_ca_key = "../certs/ca.key"
subject_postfix = ".local"

[core.allowed_mr]
allow_all = true
mrtd = []
rtmr0 = []
rtmr1 = []
rtmr2 = []
